In [158]:
# Import modules.
import pandas as pd
import numpy as np
import seaborn as sns
import re
import matplotlib.pyplot as plt
%matplotlib inline

In [159]:
# Load the dataset.
df = pd.read_csv('./data/WELLCOME_APCspend2013_forThinkful.csv', encoding = "ISO-8859-1")
df.head()
#df.shape
#df.columns

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged)
0,NaN,CUP,Psychological Medicine,Reduced parahippocampal cortical thickness in ...,£0.00
1,PMC3679557,ACS,Biomacromolecules,Structural characterization of a Model Gram-ne...,£2381.04
2,23043264 PMC3506128,ACS,J Med Chem,"Fumaroylamino-4,5-epoxymorphinans and related ...",£642.56
3,23438330 PMC3646402,ACS,J Med Chem,Orvinols with mixed kappa/mu opioid receptor a...,£669.64
4,23438216 PMC3601604,ACS,J Org Chem,Regioselective opening of myo-inositol orthoes...,£685.88

In [160]:
# Make the data lowercase.
df = df.apply(lambda x: x.astype(str).str.lower())
#df.sort_values(['Journal title'], ascending=True)
df.head()

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged)
0,nan,cup,psychological medicine,reduced parahippocampal cortical thickness in ...,£0.00
1,pmc3679557,acs,biomacromolecules,structural characterization of a model gram-ne...,£2381.04
2,23043264 pmc3506128,acs,j med chem,"fumaroylamino-4,5-epoxymorphinans and related ...",£642.56
3,23438330 pmc3646402,acs,j med chem,orvinols with mixed kappa/mu opioid receptor a...,£669.64
4,23438216 pmc3601604,acs,j org chem,regioselective opening of myo-inositol orthoes...,£685.88

In [156]:
df['Journal title'] = df['Journal title'].replace(['', ''], '')
df['Journal title'] = df['Journal title'].replace(['', ''], '')

In [161]:
df.head()

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged)
0,nan,cup,psychological medicine,reduced parahippocampal cortical thickness in ...,£0.00
1,pmc3679557,acs,biomacromolecules,structural characterization of a model gram-ne...,£2381.04
2,23043264 pmc3506128,acs,j med chem,"fumaroylamino-4,5-epoxymorphinans and related ...",£642.56
3,23438330 pmc3646402,acs,j med chem,orvinols with mixed kappa/mu opioid receptor a...,£669.64
4,23438216 pmc3601604,acs,j org chem,regioselective opening of myo-inositol orthoes...,£685.88

In [ ]:
# Removing blank spaces in Journal title
df['Journal ']

In [1]:
df.apply(lambda x: str(x).isdigit())

NameError: name 'df' is not defined

In [41]:
# Determine the 5 most common journals and the total articles for each.
df['Journal title'].value_counts()[:5]
df['Journal title'].value_counts().head(5)

plos one                           190
journal of biological chemistry     53
neuroimage                          29
plos genetics                       24
plos pathogens                      24
Name: Journal title, dtype: int64

In [42]:
# Then calc mean, median, std dev of open-access cost per article for each journal.
df.describe()

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged)
count,2127,2127,2127,2127,2127
unique,1878,275,929,2126,1402
top,nan,elsevier,plos one,"exclusive breastfeeding, diarrhoel morbidity a...",£2040.00
freq,199,391,190,2,94

In [ ]:
# Bonus: identify the open access prices paid by subject area.