In [47]:
# Import modules.
import pandas as pd
import numpy as np
import seaborn as sns
import re
import matplotlib.pyplot as plt
%matplotlib inline

In [48]:
# Load the dataset.

df = pd.read_csv('~/src/data/WELLCOME_APCspend2013_forThinkful.csv', encoding = "ISO-8859-1")
df.head()
#df.shape
#df.columns

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged),FALSE
0,PMC3378987\n,Elsevier,Academy of Nutrition and Dietetics,Parent support and parent mediated behaviours ...,£2379.54,NaN
1,PMCID: PMC3780468,ACS (Amercian Chemical Society) Publications,ACS Chemical Biology,A Novel Allosteric Inhibitor of the Uridine Di...,£1294.59,NaN
2,PMCID: PMC3621575,ACS (Amercian Chemical Society) Publications,ACS Chemical Biology,Chemical proteomic analysis reveals the drugab...,£1294.78,NaN
3,PMID: 24015914 PMC3833349,American Chemical Society,ACS Chemical Biology,Discovery of an allosteric inhibitor binding s...,£1267.76,NaN
4,: PMC3805332,American Chemical Society,ACS Chemical Biology,Synthesis of alpha-glucan in mycobacteria invo...,£2286.73,NaN

In [49]:
# Remove blank spaces in journal title

df['Journal title'] = df['Journal title'].apply(lambda x: str(x).strip())

In [50]:
# Renaming Journal titles:

df['Journal title'] = df['Journal title'].replace(['Acta Crystallographica Section D, Biological Crystallography', 'Acta Crystallographica, Section D', 'Acta Crystallography D'], 'Acta Crystallographica Section D: Biological Crystallography')
df['Journal title'] = df['Journal title'].replace(['Acta D'], 'Acta Diabetologica')
df['Journal title'] = df['Journal title'].replace(['Acta Neuropathol'], 'Acta Neuropathologica')
df['Journal title'] = df['Journal title'].replace(['Am J Bioeth'], 'American Journal of Bioethics--Neuroscience')
df['Journal title'] = df['Journal title'].replace(['Am J Trop Med Hyg'], 'American Journal of Tropical Medicine & Hygiene')
df['Journal title'] = df['Journal title'].replace(['Americal Journal of Psychiatry'], 'American Journal of Psychiatry')
df['Journal title'] = df['Journal title'].replace(['American Jnl Epidemiology'], 'American Journal of Epidemiology')
df['Journal title'] = df['Journal title'].replace(['American Journal for Clinical Nutrition'], 'American Journal of Clinical Nutrition')
df['Journal title'] = df['Journal title'].replace(['American Journal of Medical Genetics Part A'], 'American Journal of Medical Genetics')
df['Journal title'] = df['Journal title'].replace(['Anal Bioanal Chem.'], 'Analytical Biochemistry')
df['Journal title'] = df['Journal title'].replace(['Angew chems Int Ed', 'Angewande Chemie', 'Angewandte Chemie'], 'Angewandte Chemie International Edition')
df['Journal title'] = df['Journal title'].replace(['Annals of Science'], 'Annals of the New York Academy of Sciences')
df['Journal title'] = df['Journal title'].replace(['Antimicobial Agens and Chemotherapy', 'Antimicrobial Agfents and Chemotherapy'], 'Antimicrobial Agents and Chemotherapy')
df['Journal title'] = df['Journal title'].replace(['Antioxidants and Redox Signaling'], 'Antioxidants & Redox Signaling')
df['Journal title'] = df['Journal title'].replace(['Arthritis and Rheumatism'], 'Arthritis & Rheumatism')
df['Journal title'] = df['Journal title'].replace(['Arthritis Research and Therapy'], 'Arthritis Research & Therapy')
df['Journal title'] = df['Journal title'].replace(['Behavior Research and Therapy'], 'Behaviour Research and Therapy')
df['Journal title'] = df['Journal title'].replace(['Biochem Journal'], 'Biochemical Journal')
df['Journal title'] = df['Journal title'].replace(['BIOCHEM SOC TRANS'], 'Biochemical Society Transactions')
df['Journal title'] = df['Journal title'].replace(['Biochimica et Bioohysica Acta - Gene Regulatory Mechanisms'], 'Biochimica et Biophysica Acta - Molecular Basis of Disease')
df['Journal title'] = df['Journal title'].replace(['BMC Genomics.'], 'BMC Genomics')
df['Journal title'] = df['Journal title'].replace(['Britsh Journal of Psychiatry'], 'British Journal of Psychiatry')
df['Journal title'] = df['Journal title'].replace(['Brt Jnl Clinical Pharmacology'], 'British Journal of Clinical Pharmacology')
df['Journal title'] = df['Journal title'].replace(['Cell Death and Disease'], 'Cell Death & Disease')
df['Journal title'] = df['Journal title'].replace(['Cell Journal'], 'Cell')
df['Journal title'] = df['Journal title'].replace(['Cell Death Differentiation'], 'Cell Death and Differentiation')
df['Journal title'] = df['Journal title'].replace(['Cell Host and Microbe'], 'Cell Host & Microbe')
df['Journal title'] = df['Journal title'].replace(['Cell Press - Cell Reports'], 'Cell Reports')
df['Journal title'] = df['Journal title'].replace(['Cerebral Cortex Online', 'Cerebral Cortex print'], 'Cerebral Cortext')
df['Journal title'] = df['Journal title'].replace(['Child: Care, Health Development'], 'CHILD: Care, Health & Development')
df['Journal title'] = df['Journal title'].replace(['Clinicla Infectious Disease', 'Clinical Infectious Diseases Online'], 'Clinical Infectious Diseases')
df['Journal title'] = df['Journal title'].replace(['Consciousness and Cognition'], 'Consciousness & Cognition')
df['Journal title'] = df['Journal title'].replace(['Curr Biol.'], 'Current Biology')
df['Journal title'] = df['Journal title'].replace(['Current Opinion in Neurobiology'], 'Current Opinions in Neurobiology')
df['Journal title'] = df['Journal title'].replace(['Dev World Bioeth.', 'Dev. World Bioeth'], 'Developing World Bioethics')
df['Journal title'] = df['Journal title'].replace(['DEVELOPMENT CELL'], 'Developmental Cell')
df['Journal title'] = df['Journal title'].replace(['EMBO'], 'EMBO Journal')
df['Journal title'] = df['Journal title'].replace(['Epigentics'], 'Epigenetics')
df['Journal title'] = df['Journal title'].replace(['Eur J Immunol'], 'European Journal of Immunology')
df['Journal title'] = df['Journal title'].replace(['FEBS J.'], 'FEBS Journal')
df['Journal title'] = df['Journal title'].replace(['Health and Place'], 'Health & Place')

In [51]:
# Make the data lowercase.

df = df.apply(lambda x: x.astype(str).str.lower())
df.head()

,PMID/PMCID,Publisher,Journal title,Article title,COST (£) charged to Wellcome (inc VAT when charged),FALSE
0,pmc3378987\n,elsevier,academy of nutrition and dietetics,parent support and parent mediated behaviours ...,£2379.54,nan
1,pmcid: pmc3780468,acs (amercian chemical society) publications,acs chemical biology,a novel allosteric inhibitor of the uridine di...,£1294.59,nan
2,pmcid: pmc3621575,acs (amercian chemical society) publications,acs chemical biology,chemical proteomic analysis reveals the drugab...,£1294.78,nan
3,pmid: 24015914 pmc3833349,american chemical society,acs chemical biology,discovery of an allosteric inhibitor binding s...,£1267.76,nan
4,: pmc3805332,american chemical society,acs chemical biology,synthesis of alpha-glucan in mycobacteria invo...,£2286.73,nan

In [53]:
# Determine the 5 most common journals and the total articles for each.

df['Journal title'].value_counts()[:5]

plos one                           190
journal of biological chemistry     53
neuroimage                          29
nucleic acids research              26
plos pathogens                      24
Name: Journal title, dtype: int64

In [54]:
# Then calc mean, median, std dev of open-access cost per article for each journal.
# Per README file, all costs have been converted into British Pounds (£).
# However, there are still US Dollar ($) values. We will remove signs below:

df['dollar'] = df['COST (£) charged to Wellcome (inc VAT when charged)'].str.replace('$', '')
df['sterling'] = df['dollar'].str.replace('£', '')
cost = df['sterling']
stats = pd.to_numeric(cost)

In [55]:
stats.describe()

count      2127.000000
mean      24067.339972
std      146860.665559
min           0.000000
25%        1280.000000
50%        1884.010000
75%        2321.305000
max      999999.000000
Name: sterling, dtype: float64